global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
    - targets:
      - vmagent.%{SERVER_ADDRESS}:8429
- job_name: vlagent
  static_configs:
    - targets:
      - vlagent.%{SERVER_ADDRESS}:9429
- job_name: cadvisor
  static_configs:
    - targets:
      - cadvisor.%{SERVER_ADDRESS}:8080
- job_name: node
  scheme: https
  tls_config:
    ca_file: node_exporter.crt
    ## the certificate is Self-Signed so we need to skip verification
    insecure_skip_verify: true
  ## User and Password in the authentication step we have created
  basic_auth:
    username: %{NODE_EXPORTER_USER} # the user you set in the node-exporter in the node
    password: %{NODE_EXPORTER_PASS} # the plain text password which you hashed in the Encryption step
  static_configs:
    - targets: 
      - %{SERVER_ADDRESS}:9100