global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
    - targets:
      - vmagent.%{SERVER_ADDRESS}:8429
- job_name: vlagent
  static_configs:
    - targets:
      - vlagent.%{SERVER_ADDRESS}:9429
- job_name: cadvisor
  static_configs:
    - targets:
      - cadvisor.%{SERVER_ADDRESS}:8080
- job_name: node
  static_configs:
    - targets: 
      - %{SERVER_ADDRESS}:9100